# Generated by Django 2.2.3 on 2019-07-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(),
        ),
    ]
